version: '2.1'
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: yarn install
      - run: yarn run test
  coverage:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: yarn install
      - run: yarn coveralls
workflows:
  test:
    jobs:
      - test
  coverage:
    jobs:
      - coverage

