export * from './dist/continuous'
export * from './dist/discrete'

// TODO Benford                               (can be directly implemented)
// TODO Beta-binomial                         (generation unknown)
// TODO Beta-pascal / Beta negative binomial  (generation unknown)
// TODO Birnbaum-Saunders                     (requires inverse erf)
// TODO Boltzmann                             (special case of Custom)
// TODO Borel                                 (generation unknown)
// TODO Chi                                   (can be directly implemented using normal variates)
// TODO Dagum                                 (can be directly implemented)
// TODO Discrete Weibull                      (can be directly implemented)
// TODO Exponential logarithmic               (generation unknown)
// TODO Error / exponential power             (generation unknown)
// TODO Gamma/Gompertz                        (can be directly implemented)
// TODO Gamma-Poisson / negative binomial / Pascal / Polya   (can be directly implemented)
// TODO Generalized Pareto                    (can be directly implemented)
// TODO Geometric                             (can be directly implemented using exponential)
// TODO Hyperbolic-secant                     (can be directly implemented)
// TODO Hypergeometric                        (can be directly implemented)
// TODO Inverse chi2                          (can be directly implemented)
// TODO Johnson's SB                          (can be directly implemented)
// TODO Johnson's SU                          (can be directly implemented)
// TODO Levy                                  (can be directly implemented)
// TODO Log gamma                             (can be directly implemented)
// TODO Log-Laplace                           (can be directly implemented)
// TODO Logarithmic (continuous)              (requires lambertW function)
// TODO Logarithmic (discrete)                (generation unknown)
// TODO Logistic-exponential                  (can be directly implemented)
// TODO Logit-normal                          (can be directly implemented)
// TODO Makeham                               (requires lambertW function)
// TODO Muth                                  (requires lambertW function)
// TODO Nakagami                              (can be directly implemented using gamma)
// TODO Negative hypergeometric               (can be directly implemented)
// TODO Student's t                           (requires hypergeometric function)
// TODO triangular                            (can be directly implemented)
// TODO Rademacher                            (can be directly implemented)
// TODO Raised cosine                         (generation unknown)
// TODO Reciprocal                            (can be directly implemented)
// TODO Skellam                               (requires modified Bessel, cdf unkown)
// TODO U-quadratic                           (can be directly implemented)
// TODO von Mises                             (generation is unknown)
// TODO Wigner semicircle                     (can be directly implemented using beta variate)
// TODO Yule-Simon                            (can be directly implemented using exponential and geometric)
// TODO Zeta                                  (requires zeta function, harmonic number)
// TODO Zipf                                  (requires zeta function, harmonic number)
